### ISSUE TITLE
fast bro for my crush

### ISSUE THREAD

**Issue by balayogi15** [baibhavanand/lovecalc#2]

**Comment by milsponge** [comment]
Hi you'll need to deploy the code on your own server inorder for it to work. But since it is an emergency and you need it for your crush. You can use https://spongebhav.wtf/lovecalc

Leave me your email here. I will send you an email with names she tries.

**Comment by baibhavanand** [comment]
Hi you'll need to deploy the code on your own server inorder for it to work. But since it is an emergency and you need it for your crush. You can use https://spongebhav.wtf/lovecalc

Leave me your email here. I will send you an email with names she tries.

**Comment by baibhavanand** [comment]
@balayogi15

**Comment by yogeshwaran15** [comment]
mrpullingo15@gmail.com

**Comment by yogeshwaran15** [comment]
bro she tries bro lets check and send mail
bro

**Comment by baibhavanand** [comment]
Since it is not really an issue I should be tracking I am closing this issue.
